language: python
sudo: required
dist: xenial

python:
  - "3.6"
addons:
  ssh_known_hosts: georgeblackburn.co.uk:22022
os:
  - linux
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
# command to run tests
script:
  - coverage run -m unittest discover
after_success:
  - coveralls
before_deploy:
  - openssl aes-256-cbc -K $encrypted_8af44c9d6bfb_key -iv $encrypted_8af44c9d6bfb_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - chmod 600 /tmp/deploy_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/deploy_rsa
  - chmod a+x ./deploy.sh
deploy:
  # deploy develop to the staging environment
  - provider: script
    skip_cleanup: true
    script:
      - ./deploy.sh -c $TRAVIS_COMMIT -s
    on:
      branch: develop
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script:
      - ./deploy.sh -c $TRAVIS_COMMIT
    on:
      branch: master