language: python
sudo: required
dist: xenial

python:
  - "3.6"
addons:
  ssh_known_hosts: georgeblackburn.co.uk:22022
os:
  - linux
install:
  - pip install -r requirements.txt
  # Pacakages required for unit tests
  - pip install freezegun coverage coveralls
  # Pacakages required for linting
  - pip install mypy flake8
jobs:
  include:
    - stage: "Tests and Linting"
    - name: "Unit Tests"
      script: coverage run -m unittest discover
      after_success: coveralls
    - name: "Linting"
      script:
      - mypy .
      - flake8
    - stage: "Deploy"
    - name: "Deploy to Live"
      if: branch = master
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_8af44c9d6bfb_key -iv $encrypted_8af44c9d6bfb_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - chmod 600 /tmp/deploy_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add /tmp/deploy_rsa
        - chmod a+x ./deploy.sh
      deploy:
        - provider: script
          skip_cleanup: true
          script:
            - ./deploy.sh -c $TRAVIS_COMMIT
          on:
            branch: master
    - name: "Deploy to Staging"
#      if: branch = develop
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_8af44c9d6bfb_key -iv $encrypted_8af44c9d6bfb_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - chmod 600 /tmp/deploy_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add /tmp/deploy_rsa
        - chmod a+x ./deploy.sh
      deploy:
        # deploy develop to the staging environment
        - provider: script
          skip_cleanup: true
          script:
            - ./deploy.sh -c $TRAVIS_COMMIT -s