language: python
sudo: required
dist: xenial

python:
  - "3.5-dev"
  - "3.6"
  - "3.7-dev"
addons:
  ssh_known_hosts: malrig.homelinuxserver.org:22022
os:
  - linux
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover

#before_deploy:
#  - openssl aes-256-cbc -K $encrypted_79b9bbe312f6_key -iv $encrypted_79b9bbe312f6_iv -in deploy_rsa_2.enc -out /tmp/deploy_rsa -d
#  - chmod 600 /tmp/deploy_rsa
#  - eval "$(ssh-agent -s)"
#  - ssh-add /tmp/deploy_rsa
#  - chmod a+x ./deploy.sh
#deploy:
#  provider: script
#  skip_cleanup: true
#  script:
#    - ./deploy.sh
#  on:
#    branch: master
