version: 1
disable_existing_loggers: False
formatters:
    screen:
        format: "%(asctime)s - %(name)s - $(levelname)s - %(message)s"
    file:
        format: "%(asctime)s - %(name)s - $(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: screen
        stream: ext://sys.stdout

    infofilehandler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: screen
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, infofilehandler]
